import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedTambahkanKeKeranjangWidget13.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedPufferkualitaspremium100originalMemilikihighqualityFull.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedRp300000Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedJaketPufferNikeWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedImage8Widget6.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedImage38Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedRectangle116Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedNamaTokoWidget6.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedTambahkanKeKeranjangWidget12.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedBeliSekarangWidget12.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedRectangle114Widget6.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedKomentarWidget13.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedKomentarWidget12.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedImage44Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedVectorWidget52.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedRvnz_apparel_Widget2.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedKunjungiTokoWidget6.dart';
import 'package:flutterapp/thrift_20popapp/generated17pembelianjaketwidget/generated/GeneratedBeliSekarangWidget13.dart';

/* Frame 17. Pembelian Jaket
    Autogenerated by FlutLab FTF Generator
  */
class Generated17PembelianJaketWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedBeliSekarangWidget12(),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 40.0,
                child: GeneratedTambahkanKeKeranjangWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedRectangle114Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedKomentarWidget12(),
              ),
              Positioned(
                left: 28.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: GeneratedKomentarWidget13(),
              ),
              Positioned(
                left: 45.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 32.0,
                child: GeneratedTambahkanKeKeranjangWidget13(),
              ),
              Positioned(
                left: 220.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 17.0,
                child: GeneratedBeliSekarangWidget13(),
              ),
              Positioned(
                left: 20.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 26.0,
                child: GeneratedJaketPufferNikeWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 23.0,
                child: GeneratedRp300000Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 54.0,
                child:
                    GeneratedPufferkualitaspremium100originalMemilikihighqualityFull(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedImage8Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedImage44Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03740553590986464;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 13.46599292755127;

                  double percentHeight = 0.04209277629852295;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      26.939376831054688;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.03125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget52())
                  ]);
                }),
              ),
              Positioned(
                left: 25.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 40.0,
                child: GeneratedNamaTokoWidget6(),
              ),
              Positioned(
                left: 72.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 23.0,
                child: GeneratedRvnz_apparel_Widget2(),
              ),
              Positioned(
                left: 231.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle116Widget1(),
              ),
              Positioned(
                left: 242.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 14.0,
                child: GeneratedKunjungiTokoWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedImage38Widget1(),
              )
            ]),
      ),
    ));
  }
}
