import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedDAFTARWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedMASUKWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedRekomendasi2Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedSedangPromoWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedPromAkhirBulanWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedPromo99Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedDaftarWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedRekomendasi3Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedMasukWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedRekomendasiWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedRekomendasi4Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedRekomendasi5Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedRekomendasi1Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedBestSaleWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated2berandawidget/generated/GeneratedRectangle2Widget.dart';

/* Frame 2. Beranda
    Autogenerated by FlutLab FTF Generator
  */
class Generated2BerandaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 840.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -24.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 221.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 663.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 23.0,
                child: GeneratedRekomendasiWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRekomendasi1Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRekomendasi2Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRekomendasi3Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 660.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRekomendasi4Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRekomendasi5Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 210.00001525878906,
                height: 30.0,
                child: GeneratedSearchWidget(),
              ),
              Positioned(
                left: 239.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 30.0,
                child: GeneratedDaftarWidget(),
              ),
              Positioned(
                left: 295.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 30.0,
                child: GeneratedMasukWidget(),
              ),
              Positioned(
                left: 248.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 13.0,
                child: GeneratedDAFTARWidget(),
              ),
              Positioned(
                left: 305.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 13.0,
                child: GeneratedMASUKWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 60.0,
                child: GeneratedBestSaleWidget(),
              ),
              Positioned(
                left: 190.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 60.0,
                child: GeneratedSedangPromoWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 60.0,
                child: GeneratedPromo99Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 60.0,
                child: GeneratedPromAkhirBulanWidget(),
              )
            ]),
      ),
    ));
  }
}
