import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedSedangPromoWidget2.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedPromo99Widget2.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedRekomendasi7Widget4.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedImage1Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedBestSaleWidget2.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedRekomendasi6Widget4.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedRekomendasi2Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedPromAkhirBulanWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedRekomendasiWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedRekomendasi3Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedRekomendasi1Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedFotoProfilWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedSearchWidget5.dart';
import 'package:flutterapp/thrift_20popapp/generated4berandawidget/generated/GeneratedKeranjangBelanjaWidget.dart';

/* Frame 4. Beranda
    Autogenerated by FlutLab FTF Generator
  */
class Generated4BerandaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 840.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -24.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 221.0,
                child: GeneratedImage1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 663.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 23.0,
                child: GeneratedRekomendasiWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRekomendasi1Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRekomendasi2Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRekomendasi3Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 210.00001525878906,
                height: 30.0,
                child: GeneratedSearchWidget5(),
              ),
              Positioned(
                left: 250.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedKeranjangBelanjaWidget(),
              ),
              Positioned(
                left: 300.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedFotoProfilWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 60.0,
                child: GeneratedBestSaleWidget2(),
              ),
              Positioned(
                left: 190.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 60.0,
                child: GeneratedSedangPromoWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 60.0,
                child: GeneratedPromo99Widget2(),
              ),
              Positioned(
                left: 190.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 60.0,
                child: GeneratedPromAkhirBulanWidget1(),
              ),
              Positioned(
                left: 26.0,
                top: 660.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRekomendasi6Widget4(),
              ),
              Positioned(
                left: 26.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRekomendasi7Widget4(),
              )
            ]),
      ),
    ));
  }
}
