import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedVectorWidget47.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedBeliSekarangWidget2.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedStoremamenidWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedKunjungiTokoWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedRectangle114Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedJaketkualitaspremium100originalBahanTaslanWaterproofLat.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedTambahkanKeKeranjangWidget3.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedImage13Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedRectangle115Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedBeliSekarangWidget3.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedNamaTokoWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedKomentarWidget3.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedJaketTheNorthFaceWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedKomentarWidget2.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedRp750000Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedImage8Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated7pembelianbestsalewidget/generated/GeneratedTambahkanKeKeranjangWidget2.dart';

/* Frame 7. Pembelian Best Sale
    Autogenerated by FlutLab FTF Generator
  */
class Generated7PembelianBestSaleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedBeliSekarangWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 40.0,
                child: GeneratedTambahkanKeKeranjangWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 40.0,
                child: GeneratedNamaTokoWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedRectangle114Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedKomentarWidget2(),
              ),
              Positioned(
                left: 29.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: GeneratedKomentarWidget3(),
              ),
              Positioned(
                left: 45.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 32.0,
                child: GeneratedTambahkanKeKeranjangWidget3(),
              ),
              Positioned(
                left: 220.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 17.0,
                child: GeneratedBeliSekarangWidget3(),
              ),
              Positioned(
                left: 21.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 26.0,
                child: GeneratedJaketTheNorthFaceWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 23.0,
                child: GeneratedRp750000Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 80.0,
                child:
                    GeneratedJaketkualitaspremium100originalBahanTaslanWaterproofLat(),
              ),
              Positioned(
                left: 71.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 23.0,
                child: GeneratedStoremamenidWidget(),
              ),
              Positioned(
                left: 230.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle115Widget1(),
              ),
              Positioned(
                left: 241.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 14.0,
                child: GeneratedKunjungiTokoWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedImage8Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03740553590986464;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 13.46599292755127;

                  double percentHeight = 0.04209277629852295;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      26.939376831054688;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.03125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget47())
                  ]);
                }),
              ),
              Positioned(
                left: 21.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedImage13Widget(),
              )
            ]),
      ),
    ));
  }
}
