import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedImage8Widget4.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedBeliSekarangWidget9.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedBeliSekarangWidget8.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedKomentarWidget8.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedTambahkanKeKeranjangWidget9.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedVectorWidget50.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedKunjungiTokoWidget4.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedKomentarWidget9.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedTambahkanKeKeranjangWidget8.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedRectangle114Widget4.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedPufferkualitaspremium100originalMemilikihighqualityBaha.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedNamaTokoWidget4.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedImage34Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedJaketPufferTheNorthFaceWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedImage29Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedRvnz_apparel_Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedRectangle115Widget4.dart';
import 'package:flutterapp/thrift_20popapp/generated13pembelianpromoakhirbulanwidget/generated/GeneratedRp450000Widget.dart';

/* Frame 13. Pembelian Promo Akhir Bulan
    Autogenerated by FlutLab FTF Generator
  */
class Generated13PembelianPromoAkhirBulanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedBeliSekarangWidget8(),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 40.0,
                child: GeneratedTambahkanKeKeranjangWidget8(),
              ),
              Positioned(
                left: 21.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 40.0,
                child: GeneratedNamaTokoWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedRectangle114Widget4(),
              ),
              Positioned(
                left: 21.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 60.0,
                child: GeneratedKomentarWidget8(),
              ),
              Positioned(
                left: 29.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: GeneratedKomentarWidget9(),
              ),
              Positioned(
                left: 45.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 32.0,
                child: GeneratedTambahkanKeKeranjangWidget9(),
              ),
              Positioned(
                left: 220.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 17.0,
                child: GeneratedBeliSekarangWidget9(),
              ),
              Positioned(
                left: 20.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 26.0,
                child: GeneratedJaketPufferTheNorthFaceWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 23.0,
                child: GeneratedRp450000Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 67.0,
                child:
                    GeneratedPufferkualitaspremium100originalMemilikihighqualityBaha(),
              ),
              Positioned(
                left: 71.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 23.0,
                child: GeneratedRvnz_apparel_Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle115Widget4(),
              ),
              Positioned(
                left: 241.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 14.0,
                child: GeneratedKunjungiTokoWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedImage8Widget4(),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 303.0,
                child: GeneratedImage29Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03740553590986464;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 13.46599292755127;

                  double percentHeight = 0.04209277629852295;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      26.939376831054688;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.03125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget50())
                  ]);
                }),
              ),
              Positioned(
                left: 20.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedImage34Widget(),
              )
            ]),
      ),
    ));
  }
}
