import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedBeliSekarangWidget14.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedTambahkanKeKeranjangWidget15.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedKomentarWidget14.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedRvnz_apparel_Widget3.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedTopiNikeWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedNamaTokoWidget7.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedImage49Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedBeliSekarangWidget15.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedKomentarWidget15.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedVectorWidget53.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedRp150000Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedTopikualitaspremium100originalMemilikihighqualityFullTa.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedImage8Widget7.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedRectangle117Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedTambahkanKeKeranjangWidget14.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedRectangle114Widget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedKunjungiTokoWidget7.dart';
import 'package:flutterapp/thrift_20popapp/generated19pembeliankaoswidget/generated/GeneratedImage45Widget1.dart';

/* Frame 19. Pembelian Kaos
    Autogenerated by FlutLab FTF Generator
  */
class Generated19PembelianKaosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedBeliSekarangWidget14(),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 40.0,
                child: GeneratedTambahkanKeKeranjangWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedRectangle114Widget7(),
              ),
              Positioned(
                left: 20.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedKomentarWidget14(),
              ),
              Positioned(
                left: 28.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: GeneratedKomentarWidget15(),
              ),
              Positioned(
                left: 45.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 32.0,
                child: GeneratedTambahkanKeKeranjangWidget15(),
              ),
              Positioned(
                left: 220.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 17.0,
                child: GeneratedBeliSekarangWidget15(),
              ),
              Positioned(
                left: 20.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 26.0,
                child: GeneratedTopiNikeWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 23.0,
                child: GeneratedRp150000Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 67.0,
                child:
                    GeneratedTopikualitaspremium100originalMemilikihighqualityFullTa(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedImage8Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03740553590986464;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 13.46599292755127;

                  double percentHeight = 0.04209277629852295;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      26.939376831054688;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.04722222222222222,
                        translateY: constraints.maxHeight * 0.0328125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget53())
                  ]);
                }),
              ),
              Positioned(
                left: 58.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 243.0,
                child: GeneratedImage49Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 40.0,
                child: GeneratedNamaTokoWidget7(),
              ),
              Positioned(
                left: 72.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 23.0,
                child: GeneratedRvnz_apparel_Widget3(),
              ),
              Positioned(
                left: 231.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle117Widget(),
              ),
              Positioned(
                left: 242.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 14.0,
                child: GeneratedKunjungiTokoWidget7(),
              ),
              Positioned(
                left: 20.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedImage45Widget1(),
              )
            ]),
      ),
    ));
  }
}
