import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedKomentarWidget6.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedNamaTokoWidget3.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedTopiJordanWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedRp125000Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedKomentarWidget7.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedImage27Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedBeliSekarangWidget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedRectangle115Widget3.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedTambahkanKeKeranjangWidget6.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedBeliSekarangWidget6.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedRectangle114Widget3.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedImage8Widget3.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedImage22Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedTambahkanKeKeranjangWidget7.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedVectorWidget49.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedTopikualitaspremium100originalMemilikihighqualityCasual.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedPremium_capWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated11pembelianpromo99widget/generated/GeneratedKunjungiTokoWidget3.dart';

/* Frame 11. Pembelian Promo 9.9
    Autogenerated by FlutLab FTF Generator
  */
class Generated11PembelianPromo99Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedBeliSekarangWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 40.0,
                child: GeneratedTambahkanKeKeranjangWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedNamaTokoWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedRectangle114Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 61.0,
                child: GeneratedKomentarWidget6(),
              ),
              Positioned(
                left: 28.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: GeneratedKomentarWidget7(),
              ),
              Positioned(
                left: 45.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 32.0,
                child: GeneratedTambahkanKeKeranjangWidget7(),
              ),
              Positioned(
                left: 220.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 17.0,
                child: GeneratedBeliSekarangWidget7(),
              ),
              Positioned(
                left: 20.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 26.0,
                child: GeneratedTopiJordanWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 23.0,
                child: GeneratedRp125000Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 67.0,
                child:
                    GeneratedTopikualitaspremium100originalMemilikihighqualityCasual(),
              ),
              Positioned(
                left: 70.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 23.0,
                child: GeneratedPremium_capWidget(),
              ),
              Positioned(
                left: 230.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle115Widget3(),
              ),
              Positioned(
                left: 241.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 14.0,
                child: GeneratedKunjungiTokoWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedImage8Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03740553590986464;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 13.46599292755127;

                  double percentHeight = 0.04209277629852295;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      26.939376831054688;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.03125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget49())
                  ]);
                }),
              ),
              Positioned(
                left: 40.0,
                top: 18.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 280.0,
                child: GeneratedImage22Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedImage27Widget(),
              )
            ]),
      ),
    ));
  }
}
