import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedKomentarWidget10.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedTambahkanKeKeranjangWidget10.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedNamaTokoWidget5.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedTambahkanKeKeranjangWidget11.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedImage8Widget5.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedRectangle114Widget5.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedKomentarWidget11.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedImage37Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedBeliSekarangWidget10.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedImage34Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedVectorWidget51.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedKaosNirvanaWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedRectangle115Widget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedRvnz_apparel_Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedKunjungiTokoWidget5.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedRp350000Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedKaoskualitaspremium100originalMemilikihighqualityFullTa.dart';
import 'package:flutterapp/thrift_20popapp/generated15pembeliankaoswidget/generated/GeneratedBeliSekarangWidget11.dart';

/* Frame 15. Pembelian Kaos
    Autogenerated by FlutLab FTF Generator
  */
class Generated15PembelianKaosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedBeliSekarangWidget10(),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 40.0,
                child: GeneratedTambahkanKeKeranjangWidget10(),
              ),
              Positioned(
                left: 24.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 40.0,
                child: GeneratedNamaTokoWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedRectangle114Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedKomentarWidget10(),
              ),
              Positioned(
                left: 28.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: GeneratedKomentarWidget11(),
              ),
              Positioned(
                left: 45.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 32.0,
                child: GeneratedTambahkanKeKeranjangWidget11(),
              ),
              Positioned(
                left: 220.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 17.0,
                child: GeneratedBeliSekarangWidget11(),
              ),
              Positioned(
                left: 20.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 26.0,
                child: GeneratedKaosNirvanaWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 23.0,
                child: GeneratedRp350000Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 54.0,
                child:
                    GeneratedKaoskualitaspremium100originalMemilikihighqualityFullTa(),
              ),
              Positioned(
                left: 71.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 23.0,
                child: GeneratedRvnz_apparel_Widget1(),
              ),
              Positioned(
                left: 230.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle115Widget5(),
              ),
              Positioned(
                left: 241.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 14.0,
                child: GeneratedKunjungiTokoWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedImage8Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03740553590986464;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 13.46599292755127;

                  double percentHeight = 0.04209277629852295;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      26.939376831054688;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.0359375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget51())
                  ]);
                }),
              ),
              Positioned(
                left: 19.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedImage34Widget1(),
              ),
              Positioned(
                left: 43.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 274.0,
                child: GeneratedImage37Widget1(),
              )
            ]),
      ),
    ));
  }
}
