import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedTopiNewEraWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedTopikualitaspremium100originalBordirTebalLingkarKepala5.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedImage20Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedTambahkanKeKeranjangWidget4.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedVectorWidget48.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedKomentarWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedBeliSekarangWidget5.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedBeliSekarangWidget4.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedRp325000Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedRectangle114Widget2.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedNamaTokoWidget2.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedRectangle115Widget2.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedKomentarWidget5.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedKunjungiTokoWidget2.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedImage8Widget2.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedTambahkanKeKeranjangWidget5.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedImage15Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated9pembeliansedangpromowidget/generated/GeneratedPlotselingWidget.dart';

/* Frame 9. Pembelian Sedang Promo
    Autogenerated by FlutLab FTF Generator
  */
class Generated9PembelianSedangPromoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedBeliSekarangWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 40.0,
                child: GeneratedTambahkanKeKeranjangWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedNamaTokoWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedRectangle114Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedKomentarWidget4(),
              ),
              Positioned(
                left: 28.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: GeneratedKomentarWidget5(),
              ),
              Positioned(
                left: 45.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 32.0,
                child: GeneratedTambahkanKeKeranjangWidget5(),
              ),
              Positioned(
                left: 220.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 17.0,
                child: GeneratedBeliSekarangWidget5(),
              ),
              Positioned(
                left: 20.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 26.0,
                child: GeneratedTopiNewEraWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 23.0,
                child: GeneratedRp325000Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 67.0,
                child:
                    GeneratedTopikualitaspremium100originalBordirTebalLingkarKepala5(),
              ),
              Positioned(
                left: 72.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 23.0,
                child: GeneratedPlotselingWidget(),
              ),
              Positioned(
                left: 230.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle115Widget2(),
              ),
              Positioned(
                left: 241.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 14.0,
                child: GeneratedKunjungiTokoWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedImage8Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03740553590986464;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 13.46599292755127;

                  double percentHeight = 0.04209277629852295;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      26.939376831054688;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.0328125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget48())
                  ]);
                }),
              ),
              Positioned(
                left: 40.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 280.0,
                child: GeneratedImage15Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedImage20Widget(),
              )
            ]),
      ),
    ));
  }
}
