import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedBestProdukWidget31.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedVectorWidget15.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedJAKETWidget2.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedBestProdukWidget25.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedRvnz_Apparel_Widget2.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedKAOSWidget2.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedBestProdukWidget30.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedBestProdukWidget26.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedImage87Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedImage35Widget4.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedBestProdukWidget29.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedImage35Widget5.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedBestProdukWidget28.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedTOPIWidget2.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedThriftingShopWidget2.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedBestProdukWidget27.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedBestProdukWidget24.dart';
import 'package:flutterapp/thrift_20popapp/generated16profiltokowidget/generated/GeneratedLine76Widget2.dart';

/* Frame 16. Profil Toko
    Autogenerated by FlutLab FTF Generator
  */
class Generated16ProfilTokoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 975.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 975.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 4.547473508864641e-13,
                              top: 1.1368683772161603e-13,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 150.0,
                              child: GeneratedImage35Widget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.03740553590986464;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        13.46599292755127;

                                double percentHeight = 0.027630769778520633;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        26.940000534057617;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.05555555555555555,
                                      translateY: constraints.maxHeight *
                                          0.013333333333333334,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget15())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 56.0,
                              height: 56.0,
                              child: GeneratedImage35Widget5(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 86.0,
                              right: null,
                              bottom: null,
                              width: 156.0,
                              height: 29.0,
                              child: GeneratedRvnz_Apparel_Widget2(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 107.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 15.0,
                              child: GeneratedThriftingShopWidget2(),
                            ),
                            Positioned(
                              left: 81.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 21.0,
                              child: GeneratedKAOSWidget2(),
                            ),
                            Positioned(
                              left: 244.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 21.0,
                              child: GeneratedTOPIWidget2(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 21.0,
                              child: GeneratedJAKETWidget2(),
                            ),
                            Positioned(
                              left: 248.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 1.0,
                              child: GeneratedLine76Widget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 210.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget24(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget25(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 590.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget26(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 780.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget27(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 790.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedImage87Widget(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget28(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 590.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget29(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 780.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget30(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 210.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget31(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
