import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedKunjungiTokoWidget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedNamaBarangWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedVectorWidget81.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedKonfirmasiWidget2.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedVectorWidget82.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedDeskripsiBarangWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedFotoProfilWidget3.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedRectangle116Widget2.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedKomentarWidget16.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedVectorWidget83.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedBeliSekarangWidget16.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedVectorWidget80.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedNamaTokoWidget8.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedHargaBarangWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedVectorWidget84.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedKomentarWidget17.dart';
import 'package:flutterapp/thrift_20popapp/generated32tambahprodukwidget/generated/GeneratedRapidjacketWidget2.dart';

/* Frame 32. Tambah Produk
    Autogenerated by FlutLab FTF Generator
  */
class Generated32TambahProdukWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedBeliSekarangWidget16(),
              ),
              Positioned(
                left: 23.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 40.0,
                child: GeneratedNamaTokoWidget8(),
              ),
              Positioned(
                left: 20.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedKomentarWidget16(),
              ),
              Positioned(
                left: 25.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: GeneratedKomentarWidget17(),
              ),
              Positioned(
                left: 148.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 20.0,
                child: GeneratedKonfirmasiWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 25.0,
                child: GeneratedNamaBarangWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 24.0,
                child: GeneratedHargaBarangWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 80.0,
                child: GeneratedDeskripsiBarangWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03740553590986464;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 13.46599292755127;

                  double percentHeight = 0.04209277629852295;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      26.939376831054688;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.03125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget80())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07653184996710884;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 27.55146598815918;

                  double percentHeight = 0.04304916560649872;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      27.55146598815918;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.46111111111111114,
                        translateY: constraints.maxHeight * 0.2203125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget81())
                  ]);
                }),
              ),
              Positioned(
                left: 20.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 43.0,
                child: GeneratedFotoProfilWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.041666666666666664;
                  double scaleX = (constraints.maxWidth * percentWidth) / 15.0;

                  double percentHeight = 0.0234375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 15.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.9027777777777778,
                        translateY: constraints.maxHeight * 0.5078125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget82())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.041666666666666664;
                  double scaleX = (constraints.maxWidth * percentWidth) / 15.0;

                  double percentHeight = 0.0234375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 15.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.375,
                        translateY: constraints.maxHeight * 0.5546875,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget83())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.041666666666666664;
                  double scaleX = (constraints.maxWidth * percentWidth) / 15.0;

                  double percentHeight = 0.0234375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 15.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8833333333333333,
                        translateY: constraints.maxHeight * 0.6015625,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget84())
                  ]);
                }),
              ),
              Positioned(
                left: 70.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 23.0,
                child: GeneratedRapidjacketWidget2(),
              ),
              Positioned(
                left: 230.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle116Widget2(),
              ),
              Positioned(
                left: 241.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 14.0,
                child: GeneratedKunjungiTokoWidget8(),
              )
            ]),
      ),
    ));
  }
}
