import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedTOPIWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedBestProdukWidget15.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedThriftingShopWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedImage35Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedBestProdukWidget14.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedBestProdukWidget11.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedBestProdukWidget9.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedBestProdukWidget8.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedBestProdukWidget10.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedImage35Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedLine76Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedJAKETWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedRvnz_Apparel_Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedVectorWidget13.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedBestProdukWidget12.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedKAOSWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated12profiltokowidget/generated/GeneratedBestProdukWidget13.dart';

/* Frame 12. Profil Toko
    Autogenerated by FlutLab FTF Generator
  */
class Generated12ProfilTokoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 975.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 975.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 4.547473508864641e-13,
                              top: 1.1368683772161603e-13,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 150.0,
                              child: GeneratedImage35Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.03740553590986464;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        13.46599292755127;

                                double percentHeight = 0.027630769778520633;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        26.940000534057617;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.05555555555555555,
                                      translateY: constraints.maxHeight *
                                          0.013333333333333334,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget13())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 56.0,
                              height: 56.0,
                              child: GeneratedImage35Widget1(),
                            ),
                            Positioned(
                              left: 89.0,
                              top: 84.0,
                              right: null,
                              bottom: null,
                              width: 156.0,
                              height: 29.0,
                              child: GeneratedRvnz_Apparel_Widget(),
                            ),
                            Positioned(
                              left: 89.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 15.0,
                              child: GeneratedThriftingShopWidget(),
                            ),
                            Positioned(
                              left: 81.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 21.0,
                              child: GeneratedKAOSWidget(),
                            ),
                            Positioned(
                              left: 244.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 21.0,
                              child: GeneratedTOPIWidget(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 21.0,
                              child: GeneratedJAKETWidget(),
                            ),
                            Positioned(
                              left: 88.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 1.0,
                              child: GeneratedLine76Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 210.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget8(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget9(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 590.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget10(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 780.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget11(),
                            ),
                            Positioned(
                              left: 219.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget12(),
                            ),
                            Positioned(
                              left: 219.0,
                              top: 590.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget13(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 780.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget14(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 210.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget15(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
