import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated29rincianpesanandikemaswidget/generated/GeneratedRectangle99Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated29rincianpesanandikemaswidget/generated/GeneratedRincianPesananWidget3.dart';
import 'package:flutterapp/thrift_20popapp/generated29rincianpesanandikemaswidget/generated/GeneratedVectorWidget74.dart';
import 'package:flutterapp/thrift_20popapp/generated29rincianpesanandikemaswidget/generated/GeneratedRp35000Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated29rincianpesanandikemaswidget/generated/GeneratedImage60Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated29rincianpesanandikemaswidget/generated/GeneratedKembaliWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated29rincianpesanandikemaswidget/generated/GeneratedTransaksi6Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated29rincianpesanandikemaswidget/generated/GeneratedRectangle97Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated29rincianpesanandikemaswidget/generated/GeneratedImage59Widget2.dart';
import 'package:flutterapp/thrift_20popapp/generated29rincianpesanandikemaswidget/generated/GeneratedCashOnDeliveryWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated29rincianpesanandikemaswidget/generated/GeneratedPaketakanditerimapada15oktober2022Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame 29. Rincian Pesanan Dikemas
    Autogenerated by FlutLab FTF Generator
  */
class Generated29RincianPesananDikemasWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 50.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 20.0,
                child: GeneratedRincianPesananWidget3(),
              ),
              Positioned(
                left: 40.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 30.0,
                child: GeneratedKembaliWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03740553590986464;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 13.46599292755127;

                  double percentHeight = 0.04209277331829071;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      26.939374923706055;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.034375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget74())
                  ]);
                }),
              ),
              Positioned(
                left: 20.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedRectangle97Widget1(),
              ),
              Positioned(
                left: 139.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 18.0,
                child: GeneratedRp35000Widget1(),
              ),
              Positioned(
                left: 139.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 13.0,
                child: GeneratedPaketakanditerimapada15oktober2022Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 28.0,
                child: GeneratedImage59Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 150.0,
                child: GeneratedTransaksi6Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedRectangle99Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedImage60Widget1(),
              ),
              Positioned(
                left: 98.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 18.0,
                child: GeneratedCashOnDeliveryWidget1(),
              )
            ]),
      ),
    ));
  }
}
