import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated34logoutwidget/generated/GeneratedKeluarWidget2.dart';
import 'package:flutterapp/thrift_20popapp/generated34logoutwidget/generated/GeneratedApakahAndaYakinuntukKeluarSebagaiUserWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated34logoutwidget/generated/GeneratedVectorWidget85.dart';
import 'package:flutterapp/thrift_20popapp/generated34logoutwidget/generated/GeneratedYakinWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated34logoutwidget/generated/GeneratedTidakWidget.dart';

/* Frame 34.Log Out
    Autogenerated by FlutLab FTF Generator
  */
class Generated34LogOutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 50.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 23.0,
                child: GeneratedKeluarWidget2(),
              ),
              Positioned(
                left: 61.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 38.0,
                child: GeneratedApakahAndaYakinuntukKeluarSebagaiUserWidget(),
              ),
              Positioned(
                left: 60.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 30.0,
                child: GeneratedYakinWidget(),
              ),
              Positioned(
                left: 190.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 30.0,
                child: GeneratedTidakWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03740553590986464;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 13.46599292755127;

                  double percentHeight = 0.04209277629852295;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      26.939376831054688;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.034375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget85())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
