import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedRekomendasi8Widget6.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedVectorWidget66.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedBeliWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedVectorWidget65.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedRectangle50Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedDikirimWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedPesananSayaWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedImage60Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedTerakhirDilihatWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedLogOutWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedPostinganWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedImage59Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedFotoProfilWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedGroupWidget14.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedKeranjangBelanjaWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedDiterimaWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedRectangle45Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedDikemasWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedThriftingShopWidget3.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedVectorWidget70.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedAkunSayaWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedTerakhirDilihatWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated25akunwidget/generated/GeneratedRapidjacketWidget.dart';

/* Frame 25. Akun
    Autogenerated by FlutLab FTF Generator
  */
class Generated25AkunWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 160.44444274902344,
                child: GeneratedRectangle45Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 20.0,
                child: GeneratedAkunSayaWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedFotoProfilWidget1(),
              ),
              Positioned(
                left: 230.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 20.0,
                child: GeneratedPostinganWidget(),
              ),
              Positioned(
                left: 110.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 15.0,
                child: GeneratedBeliWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 121.0,
                child: GeneratedRectangle48Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 224.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 17.0,
                child: GeneratedPesananSayaWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 10.0,
                child: GeneratedKeranjangBelanjaWidget1(),
              ),
              Positioned(
                left: 123.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 10.0,
                child: GeneratedDikemasWidget(),
              ),
              Positioned(
                left: 208.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 10.0,
                child: GeneratedDikirimWidget(),
              ),
              Positioned(
                left: 285.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 10.0,
                child: GeneratedDiterimaWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 190.0,
                child: GeneratedRectangle50Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 17.0,
                child: GeneratedTerakhirDilihatWidget(),
              ),
              Positioned(
                left: 295.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 15.0,
                child: GeneratedLogOutWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03740553590986464;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 13.46599292755127;

                  double percentHeight = 0.04209277331829071;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      26.939374923706055;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.034375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget65())
                  ]);
                }),
              ),
              Positioned(
                left: 99.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 24.0,
                child: GeneratedRapidjacketWidget(),
              ),
              Positioned(
                left: 99.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 12.0,
                child: GeneratedThriftingShopWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.027777777777777776;
                  double scaleX = (constraints.maxWidth * percentWidth) / 10.0;

                  double percentHeight = 0.015625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 10.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5444444444444444,
                        translateY: constraints.maxHeight * 0.2,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget66())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1016023423936632;

                  final double height =
                      constraints.maxHeight * 0.053125041723251346;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.09166666666666666,
                        y: constraints.maxHeight * 0.4171875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget14(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.11944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 43.0;

                  double percentHeight = 0.0609375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 39.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5611111111111111,
                        translateY: constraints.maxHeight * 0.409375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget70())
                  ]);
                }),
              ),
              Positioned(
                left: 120.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedImage59Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 39.0,
                child: GeneratedImage60Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedTerakhirDilihatWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRekomendasi8Widget6(),
              )
            ]),
      ),
    ));
  }
}
