import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedKomentarWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedMarsfashion88Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedKunjungiTokoWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedKaosVintageWidget3.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedBeliSekarangWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedTambahkanKeKeranjangWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedRectangle114Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedKomentarWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedTambahkanKeKeranjangWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedRectangle115Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedImage5Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedBeliSekarangWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedImage6Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedNamaTokoWidget.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedVectorWidget46.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedRp500000Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated5pembeliankaosvintagewidget/generated/GeneratedKaoskualitaspremium100originalFulltagoriginalOversizeHa.dart';

/* Frame 5. Pembelian Kaos Vintage
    Autogenerated by FlutLab FTF Generator
  */
class Generated5PembelianKaosVintageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 23.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 40.0,
                child: GeneratedBeliSekarangWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 40.0,
                child: GeneratedTambahkanKeKeranjangWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 40.0,
                child: GeneratedNamaTokoWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedImage6Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedRectangle114Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 278.0,
                child: GeneratedImage5Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 61.0,
                child: GeneratedKomentarWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: GeneratedKomentarWidget1(),
              ),
              Positioned(
                left: 45.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 32.0,
                child: GeneratedTambahkanKeKeranjangWidget1(),
              ),
              Positioned(
                left: 220.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 17.0,
                child: GeneratedBeliSekarangWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03740553590986464;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 13.46599292755127;

                  double percentHeight = 0.04209277629852295;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      26.939376831054688;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.03125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget46())
                  ]);
                }),
              ),
              Positioned(
                left: 20.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 26.0,
                child: GeneratedKaosVintageWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 23.0,
                child: GeneratedRp500000Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 67.0,
                child:
                    GeneratedKaoskualitaspremium100originalFulltagoriginalOversizeHa(),
              ),
              Positioned(
                left: 73.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 23.0,
                child: GeneratedMarsfashion88Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle115Widget(),
              ),
              Positioned(
                left: 241.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 14.0,
                child: GeneratedKunjungiTokoWidget(),
              )
            ]),
      ),
    ));
  }
}
