import 'package:flutter/material.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedBestProdukWidget20.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedBestProdukWidget18.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedImage35Widget2.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedVectorWidget14.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedKAOSWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedLine76Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedImage35Widget3.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedBestProdukWidget22.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedRvnz_Apparel_Widget1.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedBestProdukWidget23.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedImage83Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedImage81Widget.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedTOPIWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedBestProdukWidget21.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedBestProdukWidget17.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedJAKETWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedBestProdukWidget19.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedThriftingShopWidget1.dart';
import 'package:flutterapp/thrift_20popapp/generated14profiltokowidget/generated/GeneratedBestProdukWidget16.dart';

/* Frame 14. Profil Toko
    Autogenerated by FlutLab FTF Generator
  */
class Generated14ProfilTokoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 975.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 975.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 4.547473508864641e-13,
                              top: 1.1368683772161603e-13,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 150.0,
                              child: GeneratedImage35Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.03740553590986464;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        13.46599292755127;

                                double percentHeight = 0.027630769778520633;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        26.940000534057617;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.05555555555555555,
                                      translateY: constraints.maxHeight *
                                          0.013333333333333334,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget14())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 56.0,
                              height: 56.0,
                              child: GeneratedImage35Widget3(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 86.0,
                              right: null,
                              bottom: null,
                              width: 156.0,
                              height: 29.0,
                              child: GeneratedRvnz_Apparel_Widget1(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 107.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 15.0,
                              child: GeneratedThriftingShopWidget1(),
                            ),
                            Positioned(
                              left: 81.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 21.0,
                              child: GeneratedKAOSWidget1(),
                            ),
                            Positioned(
                              left: 244.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 21.0,
                              child: GeneratedTOPIWidget1(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 21.0,
                              child: GeneratedJAKETWidget1(),
                            ),
                            Positioned(
                              left: 168.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 1.0,
                              child: GeneratedLine76Widget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 210.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget16(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget17(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 590.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget18(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 600.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedImage81Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 780.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget19(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 790.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedImage83Widget(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget20(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 590.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget21(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 780.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget22(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 210.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 150.0,
                              child: GeneratedBestProdukWidget23(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
